feat(middleware): Require workspace for /api/private calls
th33ngineers/zeno pull request #29
Opened 2023-06-28 05:27 UTC by martwozniak

Now all requests send to `/api/private/*` require passing `workspace` in url or in cookie.

2023-06-28 08:13 UTC, grski commented on middleware.ts
> +    if(request.nextUrl.searchParams.get('workspace') || request.cookies.has('workspace')){
searchParams searches through the url elements or kwargs/args?

2023-06-28 08:13 UTC, grski commented on middleware.ts
> +            status: 404,
401/403 check which is better in such case :)

2023-06-28 09:42 UTC, martwozniak commented on middleware.ts
> +    if(request.nextUrl.searchParams.get('workspace') || request.cookies.has('workspace')){
The searchParams readonly property of the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) interface returns a [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) object allowing access to the [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) decoded query arguments contained in the URL.

Source: https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams

2023-06-28 09:48 UTC, martwozniak commented on middleware.ts
> +    if(request.nextUrl.searchParams.get('workspace') || request.cookies.has('workspace')){
Example:

```
  // URL -> `/api/private/test?workspace=default`
  // `workspace` -> 'default'
```

2023-06-29 17:17 UTC, grski commented on middleware.ts
> +        return NextResponse.json({error: 401},  {
can we get the statuses abstracted away as to not use magic numbers?
eg
statuses.HTTP_401_UNAUHTORIZED = 401

then in the code
eeror: statuses.HTTP_401_UNATHOURIZED

2023-06-29 17:17 UTC, grski requested changes
check out the comment

2023-07-04 06:07 UTC, martwozniak commented
Updated

2023-07-04 06:15 UTC, grski approved these changes

2023-07-04 06:25 UTC, merged